### ISSUE TITLE
Unhandled exception for unavailable song

### ISSUE THREAD

**Issue by ericmjones** [Mostey/loadify#40]
The song in question is unavailable in my region or gone.

SpotifySharp.SpotifyException was unhandled by user code
  HResult=-2146233088
  Message=The track cannot be played
  Source=ohLibSpotify
  StackTrace:
       at SpotifySharp.SpotifyMarshalling.CheckError(SpotifyError aError)
       at SpotifySharp.SpotifySession.PlayerLoad(Track track)
       at loadify.Spotify.LoadifySession.<>c__DisplayClass16.<DownloadTrack>b__15() in
~\loadify-master\src\loadify\Spotify\LoadifySession.cs:line 192
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException:

**Comment by Mostey** [comment]
Thanks for reporting, this exception will be catched.
